# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ayush Shah
email: ayushcshah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  iOS enthusiastic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ayushcshah.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ayushcshah

# Build settings
markdown: kramdown

# Sitemap
gems:
  - jekyll-sitemap
